# SPDX-License-Identifier: AGPL-3.0-or-later
name: ClusterFuzzLite PR Fuzzing
on:
  pull_request:
    paths:
      - 'src/**'
      - 'vext-core/**'
      - 'fuzz/**'
permissions: read-all
jobs:
  pr-fuzzing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
      - uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: rust
          sanitizer: address
      - uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 300
          mode: prune
          sanitizer: address
